-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS poll_responses CASCADE;
DROP TABLE IF EXISTS rankings CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS locations;

CREATE TABLE locations (
  id SERIAL PRIMARY KEY NOT NULL,
  longitude decimal NOT NULL,
  latitude decimal NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  password VARCHAR(255),
  location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE
  );

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  poll_string VARCHAR(255) NOT NULL,
  name VARCHAR (255) NOT NULL,
  description TEXT NOT NULL,
  start_time TIMESTAMP DEFAULT now(),
  end_time TIMESTAMP
  );

CREATE TABLE options (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL,
 location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE,
 rating VARCHAR(255),
 price VARCHAR(255),
 total_review VARCHAR(255),
 address VARCHAR(255) NOT NULL,
 picture VARCHAR(255)
);

CREATE TABLE rankings (
  id SERIAL PRIMARY KEY NOT NULL
);



CREATE TABLE poll_responses (
  id  SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  option_id INTEGER NOT NULL REFERENCES options(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  ranking_id INTEGER NOT NULL REFERENCES rankings(id) ON DELETE CASCADE
  );


